HOB_HEAT="Turn on hob to low heat"

mealtime: scramble_eggs cook_beans toast_bread
	echo ""
	echo "Get a plate, a knife and a fork"
	echo "Put the toast on the plate"
	echo "Put the egg on top of the toast"
	echo "Put the beans on top of the egg and the toast (messy!)"
	echo "Eat (finally)"	
	
scramble_eggs:
	echo "Break 3 eggs into measuring jug"
	echo "Use a fork to beat the eggs until consistent"
	echo "Add a dash of salt and pepper to taste"
	echo "Put a pan on the hob"
	echo $(HOB_HEAT)
	echo "Add egg mixture to pan"
	echo "Stir the eggs until cooked to your liking"
	echo "Turn off hob"
	
cook_beans:
	echo ""
	echo "Open tin of beans"
	echo "Put a pan on the hob"
	echo "Pour bins into pan"
	echo $(HOB_HEAT)
	echo "Stir beans until cooked"
	echo "Turn off hob"
	
toast_bread:
	echo ""
	echo "Put two slices of bread into the toaster"
	echo "Turn on the toaster"
	echo "Wait for the toast to pop out"
